---
title: "three_digit_la_codes"
output: html_document
knitr: 
  eval: FALSE
---

## Background

This is a step by step guide to adding the three digit local authority codes to the wd_pcon_lad_la_rgn_ctry lookup, including the code you'll need to use.

## Step by step guide


1.  Download the three digit local authority code tables from the [Get Information about Schools](https://get-information-schools.service.gov.uk/) (GIAs) website by going to the [Local authority name and associated codes page](https://get-information-schools.service.gov.uk/Guidance/LaNameCodes), scrolling to the bottom and clicking on the 'Download' button.

    -   Save those tables in the 'data' folder of the dfeR repo. This step is temporary.

2.  Go to the [Explore Education Statistics screener repository](https://github.com/dfe-analytical-services/dfe-published-data-qa/blob/main/data/las.csv), download the 'las.csv' file.

    -  Save this file in the 'data' folder of the dfeR repo. This step is temporary.

3.  Run the code supplied below to join the data and save a new version of the lookup.

4.  Combine the data to create a master list of local authorities with three and nine digit codes.

5.  Join the local authorities data onto the wd_pcon_lad_la_rgn_ctry look up

6.  Write the data into the package using `usethis::use_data()` .

7.  Remove the screener and GIAS CSV files saved in the data folder.

8.  Update the documentation and tests if applicable by following [dfeR contributing guidance](https://dfe-analytical-services.github.io/dfeR/CONTRIBUTING.html) and using the workflow outlined.

```{r}
# Load package and dependencies
devtools::load_all()

# Load and clean LA code data from a file
load_la_codes <- function(file_path) {
  # read in data
  data.table::fread(file_path) %>%
    # rename columns
    dplyr::rename(
      la_name = 1,
      old_la_code = 2,
      new_la_code = 3
    )
}

# Combine all LA code data
all_la_codes <- dplyr::bind_rows(
  load_la_codes("data/EnglishLaNameCodes.csv"),
  load_la_codes("data/WelshLaNameCodes.csv"),
  load_la_codes("data/OtherLaNameCodes.csv")
) %>%
  # clean up the strings in the la_name column
  dplyr::mutate(
    la_name = gsub("^[A-Za-z]+ [A-Za-z]+ \\([^)]*\\) ", "", la_name),
    la_name = gsub("^[A-Za-z]+-LGR [0-9]+ ", "", la_name),
    old_la_code = as.character(old_la_code)
  )

# Identify missing LA codes from screener data
missing_3_digit_la_codes <- all_la_codes %>%
  dplyr::full_join(
    data.table::fread("data/las.csv") %>%
      dplyr::select(new_la_code, la_name, screener_old_la_code = old_la_code),
    by = c("la_name", "new_la_code")
  ) %>%
  dplyr::filter(is.na(old_la_code) & !is.na(screener_old_la_code)) %>%
  dplyr::filter(screener_old_la_code != "x") %>%
  dplyr::select(-old_la_code) %>%
  dplyr::rename(old_la_code = screener_old_la_code) %>%
  dplyr::distinct()

# Final GIAS LA codes including missing ones
gias_3_digit_la_codes <- all_la_codes %>%
  dplyr::bind_rows(missing_3_digit_la_codes)

# Join the 3 digit LA codes with the wd_pcon_lad_la_rgn_ctry look up

wd_pcon_lad_la_rgn_ctry <- dfeR::wd_pcon_lad_la_rgn_ctry %>%
  dplyr::left_join(
    gias_3_digit_la_codes,
    by = c("la_name" = "la_name",
           "new_la_code" = "new_la_code",
           "old_la_code" = "old_la_code")
  ) %>%
  # if there are NA values in old_la_code, change them to 'z'
  dplyr::mutate(old_la_code = dplyr::if_else(is.na(old_la_code),
                                             "z", old_la_code)) %>% 
  #put old_la_code before new_la_code
  dplyr::relocate(old_la_code, .before = new_la_code)


# Write the data into the package ---------------------------------------------
usethis::use_data(wd_pcon_lad_la_rgn_ctry, overwrite = TRUE)

```
